// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const schemaArg = process.argv.find((a) => a.startsWith("--schema="));
const schema = schemaArg ? schemaArg.split("=")[1] : "prisma/schema.prisma";

const isPlatform = schema === "prisma/platform.schema.prisma";
const isTenant = schema === "prisma/tenant.schema.prisma";

export default defineConfig({
  schema,
  migrations: {
    path: isPlatform
      ? "prisma/platform/migrations"
      : isTenant
        ? "prisma/tenant/migrations"
        : "prisma/migrations",
  },
  datasource: {
    url: isPlatform ? process.env.PLATFORM_DATABASE_URL : process.env.DATABASE_URL,
  },
});
